# Padronização

- Criar funções para padronização dos campos de cidade e UF.
    - Cidade: remover espaços excedentes, remover acentos e aplicar formato capitalização de título.
      Exemplo: "são paulo" → "Sao Paulo".
    - UF: remover espaços excedentes, remover acentos e converter para letras maiúsculas.
      Exemplo: "sp" → "SP".

- Salvar o tratamento em um arquivo.

In [1]:
import pandas as pd
import re
from unidecode import unidecode

In [2]:
#Função para padronizar nomes de cidades
def padronizar_cidade(texto):
    if not texto:
        return None
    #Remove espaços do início e fim
    texto = texto.strip()
    #Remove acentos
    texto = unidecode(texto)
    #Remove espaços duplicados no meio
    texto = re.sub(r'\s+', ' ', texto)
    #Title Case: "Sao Paulo"
    texto = texto.title()

    return texto

In [3]:
#Função para padronizar uf para maiúscula
def padronizar_uf(texto):
    if not texto:
        return None
    #Remove espaços do início e fim
    texto = texto.strip()
    #Remove acentos
    texto = unidecode(texto)
    #Todas maiúsculas
    texto = texto.upper()
    
    return texto

In [ ]:
#Ler o arquivo
df = pd.read_excel("cidades.xlsx")
display(df)

    cidade_destino uf_destino
0  Várzea Paulista         SP
1  varzea paulista         sp
2  Varzea paulista         Sp
3  várzea paulista         SP

In [8]:
#Aplicar as funções de padronização
df['cidade_destino'] = df['cidade_destino'].apply(padronizar_cidade)
df['uf_destino'] = df['uf_destino'].apply(padronizar_uf)

In [9]:
display(df)

    cidade_destino uf_destino
0  Varzea Paulista         SP
1  Varzea Paulista         SP
2  Varzea Paulista         SP
3  Varzea Paulista         SP

In [10]:
#Salvar arquivo padronizado
df.to_excel('cidades_padronizadas.xlsx', index=False)